apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: jqplay
  name: jqplay
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jqplay
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgres://jqplay-user:jqplay-pass@db/jqplay-db?sslmode=disable
        image: jingweno/jqplay
        name: jqplay
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
