---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: jqplay
  name: jqplay
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jqplay
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: jqplay
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgres://jqplay-user:jqplay-pass@db/jqplay-db?sslmode=disable
        image: jqplay:latest
        imagePullPolicy: IfNotPresent
        name: jqplay
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
